<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net48</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <Title>SylphyHornPlus</Title>
    <Product>SylphyHornPlus</Product>
    <Version>4.0.0</Version>
    <Authors>hwtnb</Authors>
    <Company>hwtnb.net</Company>
    <Copyright>Copyright © 2015 - 2018 Manato KAMEYA, 2021 - 2022 hwtnb</Copyright>
    <Description>Virtual Desktop Tools for Windows 11 and 10</Description>
    <AssemblyTitle>SylphyHornPlus</AssemblyTitle>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>.assets\app.green.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="ExtraVersion" Value="beta.13" />
    <AssemblyMetadata Include="OriginalCompany" Value="grabacr.net" />
    <AssemblyMetadata Include="OriginalProduct" Value="SylphyHorn" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>SylphyHorn.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>SylphyHorn.WindowsIntegrationTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release %28AppX%29|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants>TRACE;APPX</DefineConstants>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release %28AppX%29|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>TRACE;APPX</DefineConstants>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release %28AppX%29|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <DefineConstants>TRACE;APPX</DefineConstants>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug %28AppX%29|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants>TRACE;DEBUG;APPX</DefineConstants>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug %28AppX%29|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>TRACE;DEBUG;APPX</DefineConstants>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug %28AppX%29|x86'">
    <PlatformTarget>x86</PlatformTarget>
    <DefineConstants>TRACE;DEBUG;APPX</DefineConstants>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MetroRadiance">
      <HintPath>..\libraries\MetroTrilithon.Desktop\$(TargetFramework)\MetroRadiance.dll</HintPath>
    </Reference>
    <Reference Include="MetroRadiance.Chrome">
      <HintPath>..\libraries\MetroTrilithon.Desktop\$(TargetFramework)\MetroRadiance.Chrome.dll</HintPath>
    </Reference>
    <Reference Include="MetroRadiance.Core">
      <HintPath>..\libraries\MetroTrilithon.Desktop\$(TargetFramework)\MetroRadiance.Core.dll</HintPath>
    </Reference>
    <Reference Include="MetroTrilithon">
      <HintPath>..\libraries\MetroTrilithon.Desktop\$(TargetFramework)\MetroTrilithon.dll</HintPath>
    </Reference>
    <Reference Include="MetroTrilithon.Desktop">
      <HintPath>..\libraries\MetroTrilithon.Desktop\$(TargetFramework)\MetroTrilithon.Desktop.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".build\post-build.ps1" />
    <None Update="app.manifest">
      <SubType>Designer</SubType>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <AppDesigner Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SylphyHorn.Core\SylphyHorn.Core.csproj" />
    <ProjectReference Include="..\VirtualDesktop\source\VirtualDesktop.WPF\VirtualDesktop.WPF.csproj" />
    <ProjectReference Include="..\VirtualDesktop\source\VirtualDesktop\VirtualDesktop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include=".assets\tasktray.dark.ico" />
    <Resource Include=".assets\tasktray.light.ico" />
    <Resource Include=".assets\app.white.ico" />
    <Resource Include=".assets\app.green.ico" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include=".licenses\InputSimulatorPlus.txt" />
    <EmbeddedResource Include=".licenses\MetroTrilithon.txt" />
    <EmbeddedResource Include=".licenses\MetroRadiance.txt" />
    <EmbeddedResource Include=".licenses\Livet.txt" />
    <EmbeddedResource Include=".licenses\VirtualDesktop.txt" />
    <EmbeddedResource Update="Properties\Resources.ja.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.zh-hans.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include=".assets\Square150x150Logo.scale-200.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include=".assets\Square44x44Logo.scale-200.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include=".assets\Square44x44Logo.targetsize-24_altform-unplated.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include=".assets\StoreLogo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include=".assets\BadgeLogo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include=".assets\SplashScreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include=".assets\Wide310x150Logo.scale-200.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include=".assets\Square44x44Logo.scale-100.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include=".assets\Square150x150Logo.scale-100.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.ja.resx">
      <DependentUpon>Resources.resx</DependentUpon>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ElementalAnnotations-Dualism">
      <Version>1.0.2</Version>
    </PackageReference>
    <PackageReference Include="GregsStack.InputSimulatorStandard">
      <Version>1.3.5</Version>
    </PackageReference>
    <PackageReference Include="JetBrains.Annotations">
      <Version>2024.3.0</Version>
    </PackageReference>
    <PackageReference Include="LivetCask">
      <Version>4.0.2</Version>
    </PackageReference>
    <PackageReference Include="LivetExtensions">
      <Version>4.0.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.ApplicationInsights">
      <Version>2.22.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts">
      <Version>10.0.26100.1742</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf">
      <Version>1.1.135</Version>
    </PackageReference>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource">
      <Version>9.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="Application.xaml" SubType="Designer" Generator="MSBuild:Compile" />
    <Compile Update="Application.xaml.cs">
      <DependentUpon>Application.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Application.iKey.cs">
      <DependentUpon>Application.xaml</DependentUpon>
    </Compile>
    <Compile Update="Application.Static.cs">
      <DependentUpon>Application.xaml</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Remove="UI\TaskTrayTestWindow.xaml.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Compile Update="UI\TaskTrayTestWindow.xaml.cs">
      <DependentUpon>TaskTrayTestWindow.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(RunSylphyHornPostBuild)' != 'false'">
    <Exec Command="powershell -ExecutionPolicy RemoteSigned -File &quot;$(ProjectDir).build\post-build.ps1&quot; &quot;$(TargetDir)" />
  </Target>

</Project>
