//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SylphyHorn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SylphyHorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Default {
            get {
                return ResourceManager.GetString("Common_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   provided by Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ProvidedByWinows {
            get {
                return ResourceManager.GetString("Common_ProvidedByWinows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Reference {
            get {
                return ResourceManager.GetString("Common_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background {
            get {
                return ResourceManager.GetString("Settings_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the background for each desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_ChangeBackground {
            get {
                return ResourceManager.GetString("Settings_Background_ChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Desktop {
            get {
                return ResourceManager.GetString("Settings_Background_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wallpaper: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Image {
            get {
                return ResourceManager.GetString("Settings_Background_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported image formats: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Note1 {
            get {
                return ResourceManager.GetString("Settings_Background_Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note: Please prepare image files with the virtual desktop number as filename (e.g. &quot;1.png&quot;, &quot;2.png&quot;, ...). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Note2 {
            get {
                return ResourceManager.GetString("Settings_Background_Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position {
            get {
                return ResourceManager.GetString("Settings_Background_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Center {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Fill {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Fit {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Span に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Span {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stretch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Stretch {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_Position_Tile {
            get {
                return ResourceManager.GetString("Settings_Background_Position_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Background Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_SelectionDialog {
            get {
                return ResourceManager.GetString("Settings_Background_SelectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source image file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_SourceImageFile {
            get {
                return ResourceManager.GetString("Settings_Background_SourceImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source image folder path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Background_SourceImageFolder {
            get {
                return ResourceManager.GetString("Settings_Background_SourceImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close and switch to left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop_CloseAndSwitchLeft {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop_CloseAndSwitchLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close and switch to right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CloseDesktop_CloseAndSwitchRight {
            get {
                return ResourceManager.GetString("Settings_CloseDesktop_CloseAndSwitchRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop {
            get {
                return ResourceManager.GetString("Settings_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to switch to this desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_ClickToSwitchDesktop {
            get {
                return ResourceManager.GetString("Settings_Desktop_ClickToSwitchDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_CloseDesktop {
            get {
                return ResourceManager.GetString("Settings_Desktop_CloseDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close this desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_CloseDesktop_CloseThisDesktop {
            get {
                return ResourceManager.GetString("Settings_Desktop_CloseDesktop_CloseThisDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_CreateDesktop {
            get {
                return ResourceManager.GetString("Settings_Desktop_CreateDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_MoveDesktopFirst {
            get {
                return ResourceManager.GetString("Settings_Desktop_MoveDesktopFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_MoveDesktopLast {
            get {
                return ResourceManager.GetString("Settings_Desktop_MoveDesktopLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_MoveDesktopNext {
            get {
                return ResourceManager.GetString("Settings_Desktop_MoveDesktopNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_MoveDesktopPrevious {
            get {
                return ResourceManager.GetString("Settings_Desktop_MoveDesktopPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Override virtual desktops with settings of SylphyHorn on startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_OverrideSettingsOnStartup {
            get {
                return ResourceManager.GetString("Settings_Desktop_OverrideSettingsOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reorder: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_Reorder {
            get {
                return ResourceManager.GetString("Settings_Desktop_Reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Desktop_Settings {
            get {
                return ResourceManager.GetString("Settings_Desktop_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopNames {
            get {
                return ResourceManager.GetString("Settings_DesktopNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display a desktop name in notification window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopNames_UseDesktopName {
            get {
                return ResourceManager.GetString("Settings_DesktopNames_UseDesktopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop switching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loop virtual desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching_Loop {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Override OS default key combination (Ctrl+Win+Left and Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DesktopSwitching_OverrideOS {
            get {
                return ResourceManager.GetString("Settings_DesktopSwitching_OverrideOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must restart app in order for the changes to take all effect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language_RequireRestartMessage {
            get {
                return ResourceManager.GetString("Settings_Language_RequireRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language_System {
	        get {
		        return ResourceManager.GetString("Settings_Language_System", resourceCulture);
	        }
        }
        
        /// <summary>
        ///   App log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Log {
            get {
                return ResourceManager.GetString("Settings_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LogViewer {
            get {
                return ResourceManager.GetString("Settings_LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Events that occurred during execution are displayed here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_LogViewer_Description {
            get {
                return ResourceManager.GetString("Settings_LogViewer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Managing settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_Export {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export settings to an XML file to make a backup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ExportDetail {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ExportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings As... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ExportDialog {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ExportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_Import {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import settings from an XML file you stored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ImportDetail {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ImportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Settings to Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ImportDialog {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ImportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Override Desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_OverrideDesktopsConfirmationDialog {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_OverrideDesktopsConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you override virtual desktops with settings of SylphyHorn? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_OverrideDesktopsConfirmationMessage {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_OverrideDesktopsConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_Reset {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ResetConfirmationDialog {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ResetConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will delete all settings. Are you sure to reset? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ResetConfirmationMessage {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ResetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset settings to default. This will delete all settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ManagingSettings_ResetDetail {
            get {
                return ResourceManager.GetString("Settings_ManagingSettings_ResetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MouseShortcut {
            get {
                return ResourceManager.GetString("Settings_MouseShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to adjacent desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_Left {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_LeftAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_LeftAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_Right {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToAdjacentDesktop_RightAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToAdjacentDesktop_RightAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to created new desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch only: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_CreateOnly {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_CreateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_Move {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move (Switch): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToCreatedDesktop_MoveAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToCreatedDesktop_MoveAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to specified desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToSpecifiedDesktop {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToSpecifiedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToSpecifiedDesktop_Previous {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToSpecifiedDesktop_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move active window to specified desktop and switch to it に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToSpecifiedDesktopAndSwitch {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToSpecifiedDesktopAndSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MoveWindowToSpecifiedDesktopAndSwitch_Previous {
            get {
                return ResourceManager.GetString("Settings_MoveWindowToSpecifiedDesktopAndSwitch_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination displays に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All displays に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_AllDisplays {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_AllDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_CurrentDisplay {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_CurrentDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display {0}: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_MultipleDisplays_EachDisplay {
            get {
                return ResourceManager.GetString("Settings_MultipleDisplays_EachDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always show current desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_AlwaysShowDesktop {
            get {
                return ResourceManager.GetString("Settings_Notification_AlwaysShowDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display a notification when switched virtual desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display {
            get {
                return ResourceManager.GetString("Settings_Notification_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Duration for Notification Messages: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display_Duration {
            get {
                return ResourceManager.GetString("Settings_Notification_Display_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Display_Duration_Milliseconds {
            get {
                return ResourceManager.GetString("Settings_Notification_Display_Duration_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_Others {
            get {
                return ResourceManager.GetString("Settings_Notification_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple notification mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notification_SimpleMode {
            get {
                return ResourceManager.GetString("Settings_Notification_SimpleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification corner style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationCornerStyle {
            get {
                return ResourceManager.GetString("Settings_NotificationCornerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not rounded (Windows 10 style) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationCornerStyle_NotRounded {
            get {
                return ResourceManager.GetString("Settings_NotificationCornerStyle_NotRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rounded (Windows 11 style) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationCornerStyle_Rounded {
            get {
                return ResourceManager.GetString("Settings_NotificationCornerStyle_Rounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small rounded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationCornerStyle_SmallRounded {
            get {
                return ResourceManager.GetString("Settings_NotificationCornerStyle_SmallRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification font family に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontFamily {
            get {
                return ResourceManager.GetString("Settings_NotificationFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification font size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontSize {
            get {
                return ResourceManager.GetString("Settings_NotificationFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Body: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontSize_Body {
            get {
                return ResourceManager.GetString("Settings_NotificationFontSize_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontSize_Header {
            get {
                return ResourceManager.GetString("Settings_NotificationFontSize_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Spacing: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationFontSize_LineSpacing {
            get {
                return ResourceManager.GetString("Settings_NotificationFontSize_LineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification text alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Body: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Body {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Center {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Header {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Left {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationTextAlignment_Right {
            get {
                return ResourceManager.GetString("Settings_NotificationTextAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification window minimum size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize_Height {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize_Width {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize_Width_PinWindow {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize_Width_PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowMinSize_Width_SimpleMode {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowMinSize_Width_SimpleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowOffset {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowOffset_PinWindow {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowOffset_PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowOffset_SwitchDesktop {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowOffset_SwitchDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification placement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomCenter {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_BottomRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_Center {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_CenterLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_CenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_CenterRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_CenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopCenter {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopLeft {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowPlacement_TopRight {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowPlacement_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification window style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_Accent {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match to Apps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_Apps {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_Dark {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_Light {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match to System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NotificationWindowStyle_System {
            get {
                return ResourceManager.GetString("Settings_NotificationWindowStyle_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operate SylphyHornPlus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OperateSylphyHorn {
            get {
                return ResourceManager.GetString("Settings_OperateSylphyHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Pin {
            get {
                return ResourceManager.GetString("Settings_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin/Unpin toggle: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinToggle {
            get {
                return ResourceManager.GetString("Settings_PinToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window to all desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinWindow {
            get {
                return ResourceManager.GetString("Settings_PinWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin window from app to all desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PinWindowFromApp {
            get {
                return ResourceManager.GetString("Settings_PinWindowFromApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Placement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Placement {
            get {
                return ResourceManager.GetString("Settings_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShortcutKey {
            get {
                return ResourceManager.GetString("Settings_ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show only current desktop number (simple mode) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShowOnlyCurrentNumberInTray {
            get {
                return ResourceManager.GetString("Settings_ShowOnlyCurrentNumberInTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show settings: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShowSettings {
            get {
                return ResourceManager.GetString("Settings_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Startup {
            get {
                return ResourceManager.GetString("Settings_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automaticaly start at logon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Startup_Automaticaly {
            get {
                return ResourceManager.GetString("Settings_Startup_Automaticaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automaticaly start as administrator at logon (from Task Scheduler) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Startup_Automaticaly_As_Admin {
            get {
                return ResourceManager.GetString("Settings_Startup_Automaticaly_As_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap desktop (Windows 11) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop_First {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop_Last {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop_Left {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapDesktop_Right {
            get {
                return ResourceManager.GetString("Settings_SwapDesktop_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap for specified desktop (Windows 11) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwapSpecifiedDesktop {
            get {
                return ResourceManager.GetString("Settings_SwapSpecifiedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to adjacent desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchAdjacentDesktop {
            get {
                return ResourceManager.GetString("Settings_SwitchAdjacentDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchAdjacentDesktop_SwitchLeft {
            get {
                return ResourceManager.GetString("Settings_SwitchAdjacentDesktop_SwitchLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchAdjacentDesktop_SwitchRight {
            get {
                return ResourceManager.GetString("Settings_SwitchAdjacentDesktop_SwitchRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch to specified desktop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop_Add {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop_Previous {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove last に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop_RemoveLast {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop_RemoveLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resize to fit desktops に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SwitchSpecifiedDesktop_ResizeToFit {
            get {
                return ResourceManager.GetString("Settings_SwitchSpecifiedDesktop_ResizeToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TaskView {
            get {
                return ResourceManager.GetString("Settings_TaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Task View: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TaskView_ShowTaskView {
            get {
                return ResourceManager.GetString("Settings_TaskView_ShowTaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch Window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TaskView_ShowWindowSwitch {
            get {
                return ResourceManager.GetString("Settings_TaskView_ShowWindowSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle desktop notification: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ToggleDesktopNotification {
            get {
                return ResourceManager.GetString("Settings_ToggleDesktopNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show current desktop info in tray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ToggleTrayIconInfo {
            get {
                return ResourceManager.GetString("Settings_ToggleTrayIconInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tray Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TrayIcon {
            get {
                return ResourceManager.GetString("Settings_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unpin window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Unpin {
            get {
                return ResourceManager.GetString("Settings_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application is running in the background. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_FirstTimeMessage {
            get {
                return ResourceManager.GetString("TaskTray_FirstTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit (X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_Menu_Exit {
            get {
                return ResourceManager.GetString("TaskTray_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Settings (S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_Menu_Settings {
            get {
                return ResourceManager.GetString("TaskTray_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Desktop {0}/{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTray_TooltipText_DesktopCount {
            get {
                return ResourceManager.GetString("TaskTray_TooltipText_DesktopCount", resourceCulture);
            }
        }
    }
}
